# Generated by Django 2.2.1 on 2019-07-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_no', models.IntegerField()),
                ('date_created', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('voucher_no', models.CharField(max_length=50)),
                ('voucher_created_date', models.DateField()),
                ('paid_to', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher_particulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='voucher.Voucher')),
            ],
        ),
    ]
