# Generated by Django 2.2.1 on 2019-07-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BracketSSContribEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrib_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('ranged', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='General_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_company', models.CharField(default='company', max_length=255)),
            ],
        ),
    ]
