# Generated by Django 2.2.1 on 2019-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_settings',
            name='template_name',
            field=models.CharField(default='Company Inc.', max_length=255),
        ),
    ]
