# Generated by Django 2.2.1 on 2019-07-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0002_general_settings_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_settings',
            name='company_address',
            field=models.CharField(default='Company Location', max_length=255),
        ),
    ]
