# Generated by Django 2.2.1 on 2019-07-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0003_general_settings_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_settings',
            name='company_contacts',
            field=models.CharField(default='02 xxx-xxxx / 02 xxx-xxxx', max_length=255),
        ),
    ]
